#!/usr/bin/env bash
##!/bin/bash

# go to working dir
pwd="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || exit 1
cd "$pwd" || exit 1
parent_dir=$(dirname "${pwd}")

# parse config
function get_setting() {
  grep -Ev '^\s*$|^\s*\#' "$2" | grep -E "\s*$1\s*=" | sed 's/.*=//; s/^ //g'
}

function check_setting() {
  if [[ $(wc -l <<<"$1") -gt 1 ]]; then
    echo "multiple values found, 1 expected" >&2
    exit 1
  fi
}

# get settings from config
project_id=$(get_setting "ID" ../.env)
check_setting "$project_id"

# todo reuse or remove old stuff
[ -n "$project_id" ] && {
  printf "Found project name: %s\n" "${project_id}"
  old_volumes=$(docker volume ls -q --filter="name=${project_id}$")
  [ -n "$old_volumes" ] && ./remove_project
}

# set project id
# todo wording, enter name or empty for id
#while [ $is_valid -eq 0 ] && [ $old_container -eq 1 ]; do
printf "Please enter a project name or leave empty for an automatic ID to be assigned to this instance: "
read -r user_input


case $user_input in
"")
  # todo while valid (check if exists)
  project_id=$(uuidgen | md5 | cut -c-12) # | cut -c-12
  echo "id: " "$project_id"
  ;;
(*[!abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890_.-]*)
  echo >&2 "That ID is not allowed. Please use only characters [a-zA-Z0-9_.-]"
  exit 1
  ;;
*)
  project_id=$user_input
  #    printf "Enter project name:\n"
  #    read -r project_id
  # todo while valid (check if exists)
  ;;
esac
#done

# write to .env
echo "ID=${project_id}" >../.env

# volumes
# todo extrenal script
# volume-paths array
paths=(
  "fms-admin-conf-${project_id}" "/Admin/conf/"
  "fms-data-backups-${project_id}" "/Data/Backups/"
  "fms-data-databases-${project_id}" "/Data/Databases/"
  "fms-data-preferences-${project_id}" "/Data/Preferences/"
  "fms-dbserver-extensions-${project_id}" "/Database Server/Extensions/"
  "fms-conf-${project_id}" "/conf/"
  "fms-http-dotconf-${project_id}" "/HTTPServer/.conf/"
  "fms-http-conf-${project_id}" "/HTTPServer/conf/"
  "fms-http-logs-${project_id}" "/HTTPServer/logs/"
  "fms-logs-${project_id}" "/Logs/"
  "fms-webpub-conf-${project_id}" "/Web Publishing/conf/"
)

## create directories
#printf "\n\e[34mCreating directories on host...\e[39m\n"
#for ((i = 1; i < "${#paths[@]}"; i += 2)); do
#  if [[ ! -d "fms-data${paths[$i]}" ]]; then
#    mkdir -p -- "fms-data${paths[$i]}"
#  fi
#done

# create bind volumes
printf "\n\e[34mcreating volumes...\e[39m\n"
for ((i = 0; i < "${#paths[@]}"; i += 2)); do
  docker volume create --driver local -o o=bind -o type=none -o device="$parent_dir/fms-data${paths[$i + 1]}" "${paths[$i]}" || {
    printf "error while creating docker volumes"
    exit 1
  }
done

printf "\ndone\n"
exit 0
